openapi: 3.0.1
info:
  title: readFile
  description: API Definition of readFile
  version: 1.0.0
servers:
- url: http://localhost:8290/read
paths:
  /:
    get:
      responses:
        default:
          description: Default response
