openapi: 3.0.1
info:
  title: sample
  description: API Definition of sample
  version: '1.0'
servers:
- url: http://localhost:8290/sample
paths:
  /sample/{category}:
    get:
      parameters:
      - name: category
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
